### ISSUE TITLE
Expecting VirtualIPs but got Spec

### ISSUE THREAD

**Issue by trajano** [mohsenasm/swarm-dashboard#19]
The server seems to be yielding the following error message

    Expecting an object with a field named `VirtualIPs` at _.services[12].Endpoint but instead got: {"Spec":{}}

![image](https://user-images.githubusercontent.com/110627/43118593-89810b18-8ee0-11e8-86c4-13fb3ed17a5d.png)

**Comment by trajano** [comment]
I found that it is because of a specific stack.  Here's my config file 

```
version: '3.4'
services:
  forward:
    image: marcnuri/port-forward
    depends_on:
    - consul
    networks:
    - consul
    environment:
    - 'REMOTE_HOST=consul'
    - 'REMOTE_PORT=8500'
    - 'LOCAL_PORT=8500'
    ports:
    - 8500:8500
    deploy:
      replicas: 3
  consul:
    image: consul
    command: agent -server -retry-join=consul -bootstrap-expect=3 -client=0.0.0.0
    networks:
    - consul
    environment:
    - 'CONSUL_BIND_INTERFACE=eth0'
    deploy:
      replicas: 3
      endpoint_mode: dnsrr
networks:
  consul: 
    driver: overlay
    attachable: false
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24

```

When executed the consul service has `_.EndPoint == { Spec {} }`
