### ISSUE TITLE
Need a proper ARM build

### ISSUE THREAD

**Issue by trajano** [mohsenasm/swarm-dashboard#30]
I tried to deploy the build on a Raspberry Pi
```
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
exec /sbin/tini: exec format error
```

I suspect it's because you're supporting LetsEncrypt and the binaries you are using to run the cron are not platform neutral

**Comment by trajano** [comment]
Here's a snippet from my old project that builds multiarch

https://github.com/trajano/spring-cloud-demo/blob/78ad12e7db4198fbedd94d2b2a4e87f5ae5ff187/.github/workflows/publish.yml#L63-L104

You'd likely need that in the end but there's still the first problem of ensuring you have a multi-arch base for tini

**Comment by mohsenasm** [comment]
We are using `apk` to install `tini`, and it apparently supports ARM.
https://pkgs.alpinelinux.org/packages?name=tini&branch=edge&repo=&arch=&maintainer=
https://pkgs.alpinelinux.org/packages?name=lego&branch=edge&repo=&arch=&maintainer=

We should probably just change the docker push workflow and Lego installation.

**Comment by trajano** [comment]
If we follow the same pattern as that `tini` I guess we can simply do a `if` condition.

**Comment by mohsenasm** [comment]
I have added support for `linux/arm64/v8`, but I don't have a Raspberry Pi to test it.
Docker image: `mohsenasm/swarm-dashboard:dev_multiarch`

----

I also tried adding support for `linux/arm/v7` and `linux/arm/v6`, but `yarn install` didn't finish even after two hours. It also didn't produce any logs, even with the `verbose` flag.
The problem seems to be because of QEMU Emulation (https://github.com/nodejs/docker-node/issues/1335) or attempting to build the modules from the source (https://stackoverflow.com/questions/24961623).

**Comment by trajano** [comment]
Tried it's on a restart loop.

**Comment by mohsenasm** [comment]
This can be a `healthcheck` issue.
I temporarily disabled the `healthcheck` to see if it is the case.

Is there any related log in the `docker service logs` or `docker container inspect <container_id>`?

**Comment by trajano** [comment]
I did --no-healthcheck​ it just stops after a while.
________________________________

**Comment by trajano** [comment]
```
trajano@nas:~/trajano.net$ docker service logs -f trajano_vis
trajano_vis.1.v2qwk5ml6ouq@nas    | crond: crond (busybox 1.36.1) started, log level 8
trajano_vis.1.v2qwk5ml6ouq@nas    | HTTP server listening on 8080
trajano_vis.1.v2qwk5ml6ouq@nas    | crond: USER root pid  32 cmd run-parts /etc/periodic/15min
trajano_vis.1.v2qwk5ml6ouq@nas    | crond: USER root pid  33 cmd run-parts /etc/periodic/hourly
trajano_vis.1.v2qwk5ml6ouq@nas    | crond: USER root pid  34 cmd run-parts /etc/periodic/15min
trajano_vis.1.wtvt439q5urr@nas    | crond: crond (busybox 1.36.1) started, log level 8
trajano_vis.1.wtvt439q5urr@nas    | HTTP server listening on 8080
```

**Comment by trajano** [comment]
Building on the pi
```
 => [elm-build 2/8] RUN npm install --unsafe-perm -g elm@latest-0.18.0 --silent                                                                                                                  39.8s
 => => # /usr/local/bin/elm -> /usr/local/lib/node_modules/elm/bin/elm
 => => # /usr/local/bin/elm-make -> /usr/local/lib/node_modules/elm/bin/elm-make
 => => # /usr/local/bin/elm-package -> /usr/local/lib/node_modules/elm/bin/elm-package
 => => # /usr/local/bin/elm-reactor -> /usr/local/lib/node_modules/elm/bin/elm-reactor
 => => # /usr/local/bin/elm-repl -> /usr/local/lib/node_modules/elm/bin/elm-repl
 => => # No binaries are available for your platform: linux-arm64
```

**Comment by trajano** [comment]
It won't open up the port for me so nothing is listening.

I guess Elm won't have an ARM specific build anytime soon so this block may be needed to build a platform specific elm

```Dockerfile
# syntax=docker/dockerfile:1-labs
FROM debian:bullseye AS elm
RUN --mount=type=cache,target=/var/cache/apt \
  apt-get update && \
  apt-get install -y build-essential \
    automake \
    autotools-dev \
    make \
    g++ \
    ca-certificates \
    software-properties-common \
    apt-transport-https \
    lsb-base \
    lsb-release \
    zlib1g-dev \
    libpcre3-dev \
    libcurl4-openssl-dev \
    libc-dev \
    libxml2-dev \
    libsnmp-dev \
    libssh2-1-dev \
    libevent-dev \
    libopenipmi-dev \
    libpng-dev \
    pkg-config \
    libfontconfig1 \
    git \
    bzip2 \
    zip \
    unzip \
    musl-dev \
    ghc \
    cabal-install \
    libmpfr-dev
ADD --keep-git-dir=true https://github.com/elm/compiler.git#0.19.1 /w/compiler
WORKDIR /w/compiler
RUN rm worker/elm.cabal
RUN cabal new-update
RUN cabal new-configure
RUN cabal new-build
```

**Comment by trajano** [comment]
Thanks I got it to build and deploy

curl -v https://trajano.net/swarm-visualizer/

Missing metrics though #31

**Comment by mohsenasm** [comment]
Is it working now?
What was the problem?

**Comment by trajano** [comment]
> Is it working now? What was the problem/sloution?

From the documentation I presumed these were defaulted

      NODE_EXPORTER_SERVICE_NAME_REGEX: "node-exporter"
      CADVISOR_SERVICE_NAME_REGEX: "cadvisor"


But it seems I had to explicity set it in the environment.

**Comment by trajano** [comment]
Note this is a personal build so it's not ideal.

**Comment by mohsenasm** [comment]
> Note this is a personal build so it's not ideal.

So you only rebuild the image with one that [I posted](https://github.com/mohsenasm/swarm-dashboard/issues/30#issuecomment-1781737888), and it worked?

No change in the compose.yml file or anything else?

---

> From the documentation I presumed these were defaulted
> 
> ```
>   NODE_EXPORTER_SERVICE_NAME_REGEX: "node-exporter"
>   CADVISOR_SERVICE_NAME_REGEX: "cadvisor"
> ```

The default is not using `cadvisor` and `node-exporter`, because of backward compatibility.

**Comment by trajano** [comment]
Slight modification so I can test both locally and on the server.  But same result

```Dockerfile
FROM node:20-alpine AS base
RUN apk add --update tini lego curl && rm -r /var/cache
ENTRYPOINT ["/sbin/tini", "--"]
WORKDIR /home/node/app

FROM base AS dependencies
ENV NODE_ENV production
COPY package.json yarn.lock ./
RUN yarn install --production

FROM node:20-alpine AS base2
WORKDIR /w/
ADD https://github.com/mohsenasm/swarm-dashboard/files/13181678/index.js.zip /w
RUN unzip index.js.zip

FROM base AS release
WORKDIR /home/node/app
ENV LEGO_PATH=/lego-files

COPY --from=dependencies /home/node/app/node_modules node_modules
COPY --from=base2 /w/index.js client/index.js
COPY ./elm-client/client client
COPY server server
COPY server.sh server.sh
COPY healthcheck.sh healthcheck.sh
COPY crontab /var/spool/cron/crontabs/root

ENV PORT=8080
# HEALTHCHECK --interval=60s --timeout=30s \
#   CMD sh healthcheck.sh

# Run under Tini
CMD ["sh", "server.sh"]
```
My relevant compose file blocks (I added to my uber compose file)
```
  vis:
    # image: mohsenasm/swarm-dashboard:dev_multiarch
    image: trajano/sasha
    environment:
      PATH_PREFIX: /swarm-visualizer
      NODE_EXPORTER_SERVICE_NAME_REGEX: "node-exporter"
      CADVISOR_SERVICE_NAME_REGEX: "cadvisor"
    networks:
      - traefik
      - default
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # logging:
    #   driver: "none"
    deploy:
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 128M
      placement:
        constraints:
          - "node.role==manager"
      labels:
        - traefik.enable=true
        - traefik.http.routers.swarm-visualizer.rule=PathPrefix(`/swarm-visualizer`)
        - traefik.http.routers.swarm-visualizer.entryPoints=https
        - traefik.http.services.swarm-visualizer.loadbalancer.server.port=8080
  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.6.1
    volumes:
      - '/:/host:ro'
    command:
      - '--path.rootfs=/host'
    deploy:
      mode: global
      resources:
        reservations:
          memory: 64M
        limits:
          memory: 64M

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro
      - /dev/kmsg:/dev/kmsg:ro
    cap_add:
      - SYSLOG
    privileged: true
    deploy:
      mode: global
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 128M
```
